### ISSUE TITLE
kibelasync pull をするとエラーになる。

### ISSUE THREAD

**Issue by rito-aither** [Songmu/kibelasync#4]
事象としましては

下記コマンドでインストール
`go get github.com/Songmu/kibelasync/cmd/kibelasync`

環境変数を設定
`kibelasync pull`を打つ

そうしますと下記のエラーになってしまいます。
`
[kibelasync] failed to pullNotes: failed to ki.listNodeIDs: failed to ki.getNotesCount: API response with code: 400, response: {"errors":[{"message":"Parse error on \")\" (RPAREN) at [2, 9]","extensions":{"code":"PARSE_ERROR"}}]}`

確認のほどよろしくお願いいたします。

**Comment by Songmu** [comment]
@rito-aither レポートありがとうございます！クエリの互換性が壊れてしまっており、追随しました。v0.0.4で治っているはずです。ご確認ください。

**Comment by rito-aither** [comment]
@Songmu 修正ありがとうございます！
無事取得(pull),編集(push),新規作成(publish)できました！

素早い修正ありがとうございました。
これでkibelaでのドキュメント管理が楽になります！
